Document: pebble-remote
Title: Debian pebble-remote Manual
Author: <insert document author here>
Abstract: This manual describes what pebble-remote is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/pebble-remote/pebble-remote.sgml.gz

Format: postscript
Files: /usr/share/doc/pebble-remote/pebble-remote.ps.gz

Format: text
Files: /usr/share/doc/pebble-remote/pebble-remote.text.gz

Format: HTML
Index: /usr/share/doc/pebble-remote/html/index.html
Files: /usr/share/doc/pebble-remote/html/*.html
